### ISSUE TITLE
Unsupported (valid) appveyor syntax

### ISSUE THREAD

**Issue by jugmac00** [mgedmin/check-python-versions#12]
**Reproduction**
```
$ git clone https://github.com/untitaker/python-atomicwrites 
# current head of master at time of issue creation 97d60c40406affbc1978c9197ed899653b1b6c7a

$ check-python-versions --version
check-python-versions version 0.13.0

$ check-python-versions 
setup.py says:              2.7, 3.4, 3.5, 3.6, 3.7
- python_requires says:     2.7, 3.4, 3.5, 3.6, 3.7, 3.8
tox.ini says:               2.7, 3.4, 3.5, 3.6, PyPy
.travis.yml says:           2.7, 3.4, 3.5, 3.6, 3.7, PyPy
Traceback (most recent call last):
  File "/usr/local/bin/check-python-versions", line 11, in <module>
    sys.exit(main())
  File "/home/jugmac00/Virtualenvironments/check-python-versions/lib/python3.8/site-packages/check_python_versions/cli.py", line 305, in main
    _main()
  File "/home/jugmac00/Virtualenvironments/check-python-versions/lib/python3.8/site-packages/check_python_versions/cli.py", line 287, in _main
    if not check_versions(path, expect=args.expect,
  File "/home/jugmac00/Virtualenvironments/check-python-versions/lib/python3.8/site-packages/check_python_versions/cli.py", line 146, in check_versions
    versions = extractor(filename_or_replacement(pathname, replacements))
  File "/home/jugmac00/Virtualenvironments/check-python-versions/lib/python3.8/site-packages/check_python_versions/parsers/appveyor.py", line 25, in get_appveyor_yml_python_versions
    versions.append(appveyor_normalize_py_version(value))
  File "/home/jugmac00/Virtualenvironments/check-python-versions/lib/python3.8/site-packages/check_python_versions/parsers/appveyor.py", line 42, in appveyor_normalize_py_version
    assert len(ver) >= 2 and ver[:2].isdigit()
AssertionError
```

The `appveyor` config looks like...
https://github.com/untitaker/python-atomicwrites/blob/97d60c40406affbc1978c9197ed899653b1b6c7a/appveyor.yml#L1-L19

The configuration seems to be valid, as CI works
https://ci.appveyor.com/project/untitaker/python-atomicwrites/branch/master

P.S.: I am not affiliated with `atomicwrites`, it just looks like `pytest` is using it, and I happen to use `pytest` for my Zope app. And also I never use `appveyor` myself.

**Comment by mgedmin** [comment]
It was the forward slashes that did it.

**Comment by jugmac00** [comment]
Thanks a ton!

Current master works like a charm!

```
python-atomicwrites on  modernize-python-versions via 🐍 v3.8.2 (venv)
❯ check-python-versions 
setup.py says:              2.7, 3.4, 3.5, 3.6, 3.7, 3.8
- python_requires says:     2.7, 3.4, 3.5, 3.6, 3.7, 3.8
tox.ini says:               2.7, 3.4, 3.5, 3.6, 3.7, 3.8, PyPy
.travis.yml says:           2.7, 3.4, 3.5, 3.6, 3.7, 3.8, PyPy
appveyor.yml says:          2.7, 3.4, 3.5, 3.6, 3.7, 3.8
```
